import type { Metadata } from "next";
import "./globals.css";
import Navbar from "components/Navbar";

export const metadata: Metadata = {
  title: "Arzinaja Test",
  description: "Generated by Arzinaja Test",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body>
        <Navbar /> {children}
      </body>
    </html>
  );
}
